#!/bin/bash

echo "Script Di Mulai Pada $(date)"

if [ ! -f /var/log/xray/access.log ]; then

echo  "File /var/log/xray/access.log    tidak ditemukan!"

exit1

fi

user_count=   $(grep    "accepted"  /var/log/xray/access.log  |  grep -v  "127.0.0.1"  |  awk '{print $4}'  | sort | uniq | wc -l)

echo         "jumlah    pengguna     connected: $user_count"

echo      "$(date):   Jumlah pengguna saat ini: $user_count" >> /var/log/xray/monitor/log

if [  "$user_count"  -ge 50 ]; then

echo  "$(date):  Jumlah connected mencapai $user_count.  Merestart service Xray..." >> /var/log/xray/monitor/log

sudo systemctl restart xray.service

echo  "Service Xray Berhasil Di restart"

else

echo  "Jumlah connected belom mencapai untuk restart."

fi